### ISSUE TITLE
frequent unable to locate 'okta-signin-username' element

### ISSUE THREAD

**Issue by pfunkmallone** [dejanzelic/coxusage-docker#1]
Behavior seems inconsistent. I'm having spurious "unable to locate element:  {"method":"css selector","selector":"[id="okta-signin-username"]"} errors.

And when it does go through successfully, it's not writing my output file. How can I help debug?

**Comment by pfunkmallone** [comment]
...OK figured out why the file doesn't write...a user's JSON_LOCATION **MUST** include the /data/ path.

**Comment by dejanzelic** [comment]
I wasn't receiving the "unable to locate element" error, but I believe that it might have been because the wait wasn't long enough. Could you give it a try now and see if that fixes it? If so, I can spend some times and replace all the "sleeps" with the appropriate waits.

**Comment by pfunkmallone** [comment]
Will run some tests this evening. I agree that waits would be the most failproof solution. I'm going to need to dig into Selenium to learn. Your script made me realize how simple it is to use. Thanks

**Comment by pfunkmallone** [comment]
I see you added the visibility_of_element_located. That worked great! Thanks for this!
